### ISSUE TITLE
Fix incorrect application flow

### ISSUE THREAD

**Issue by TreyT-FSD** [TreyT-FSD/Phase1_Project#1]
Main menu should have 3 options

1. view files
2. navigate to next level of user interface where add/remove/search operations are
3. exit applications

current implementation only has one menu level.

**Comment by treyturley** [comment]
**Todo**
- [x] Implement Home Menu
- [x] Implement File Menu
- [x] Validate that the correct messages are displayed to the user for each file interaction

**Comment by treyturley** [comment]
The delete operation needs to return a message if the file is not found.
![image](https://user-images.githubusercontent.com/81778542/116788039-16773380-aa6d-11eb-99b7-3f066f7ee1e9.png)

**Comment by treyturley** [comment]
Issue #6 covers fixing the file not found message for the delete operation.
